print('Digite um número inteiro para ver sua tabuada')
n =int(input('Diga um numero:'))
print(n,'x 1  = ',(n*1))
print(n,'x 2  = ',(n*2))
print(n,'x 3  = ',(n*3))
print(n,'x 4  = ',(n*4))
print(n,'x 5  = ',(n*5))
print(n,'x 6  = ',(n*6))
print(n,'x 7  = ',(n*7))
print(n,'x 8  = ',(n*8))
print(n,'x 9  = ',(n*9))
print(n,'x 10 = ', (n*10))

print('='*9,'OU','='*9)

print('{:2} x {} = {}'.format(1, n, n*1))
print('{:2} x {} = {}'.format(2, n, n*2))
print('{:2} x {} = {}'.format(3, n, n*3))
print('{:2} x {} = {}'.format(4, n, n*4))
print('{:2} x {} = {}'.format(5, n, n*5))
print('{:2} x {} = {}'.format(6, n, n*5))
print('{:2} x {} = {}'.format(7, n, n*5))
print('{:2} x {} = {}'.format(8, n, n*5))
print('{:2} x {} = {}'.format(9, n, n*5))
print('{:2} x {} = {}'.format(10, n, n*5))
