print('==========Exercicio #3=======')
nome=input('Qual é seu nome?')
print('É um prazer te conhecer ',nome, 'Agora me diz...')
idade=input('Qual sua idade?')
print('Muito bem')
dia=input('Que dia você nasceu?')
mes=input('E o mes?')
print('Certo, deixa eu conferir')
print('Seu nome é ',nome,'você tem',idade,' anos, e nasceu no dia ',dia,' de ',mes,' .Certo?')
