print('Analisador de nomes!')
nome=str(input('Digite seu nome: ')).strip()
print('Analisando seu nome...')
print('Seu nome em minusculas é: {}'.format(nome.lower()))
print('Seu nome em maiusculas é: {}'.format(nome.upper()))
print('Seu nome ao todo tem {} letras'.format(len(nome)-nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
nome2=nome.split()
print('Seu primeiro nome é {}, e ele tem {} letras!'.format(nome2[0], len(nome2[0])))